



#!/usr/bin/env python3
"""
Fixtures for GitHub API integration tests.
"""

org_payload = {
    "login": "google",
    "id": 1342004,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
    "url": "https://api.github.com/orgs/google",
    "repos_url": "https://api.github.com/orgs/google/repos",
    "events_url": "https://api.github.com/orgs/google/events",
    "hooks_url": "https://api.github.com/orgs/google/hooks",
    "issues_url": "https://api.github.com/orgs/google/issues",
    "members_url": "https://api.github.com/orgs/google/members{/member}",
    "public_members_url": "https://api.github.com/orgs/google/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/1342004?v=4",
    "description": "Google, but for Developers",
    "name": "Google",
    "company": None,
    "blog": "https://developers.google.com/",
    "location": "Mountain View, CA",
    "email": None,
    "has_organization_projects": True,
    "has_repository_projects": True,
    "public_repos": 353,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "html_url": "https://github.com/google",
    "created_at": "2007-11-28T14:47:33Z",
    "updated_at": "2024-07-17T19:30:18Z",
    "type": "Organization",
}

repos_payload = [
    {
        "id": 123456789,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMjM0NTY3ODk=",
        "name": "repo_1",
        "full_name": "google/repo_1",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1342004?v=4",
        },
        "html_url": "https://github.com/google/repo_1",
        "description": "A sample repository.",
        "fork": False,
        "url": "https://api.github.com/repos/google/repo_1",
        "forks_url": "https://api.github.com/repos/google/repo_1/forks",
        "keys_url": "https://api.github.com/repos/google/repo_1/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/google/repo_1/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/google/repo_1/teams",
        "hooks_url": "https://api.github.com/repos/google/repo_1/hooks",
        "issue_events_url": "https://api.github.com/repos/google/repo_1/issues/events{/number}",
        "events_url": "https://api.github.com/repos/google/repo_1/events",
        "assignees_url": "https://api.github.com/repos/google/repo_1/assignees{/user}",
        "branches_url": "https://api.github.com/repos/google/repo_1/branches{/branch}",
        "tags_url": "https://api.github.com/repos/google/repo_1/tags",
        "blobs_url": "https://api.github.com/repos/google/repo_1/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/google/repo_1/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/google/repo_1/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/google/repo_1/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/google/repo_1/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/google/repo_1/languages",
        "stargazers_url": "https://api.github.com/repos/google/repo_1/stargazers",
        "contributors_url": "https://api.github.com/repos/google/repo_1/contributors",
        "subscribers_url": "https://api.github.com/repos/google/repo_1/subscribers",
        "subscription_url": "https://api.github.com/repos/google/repo_1/subscription",
        "commits_url": "https://api.github.com/repos/google/repo_1/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/google/repo_1/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/google/repo_1/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/google/repo_1/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/google/repo_1/contents/{+path}",
        "compare_url": "https://api.github.com/repos/google/repo_1/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/google/repo_1/merges",
        "archive_url": "https://api.github.com/repos/google/repo_1/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/google/repo_1/downloads",
        "issues_url": "https://api.github.com/repos/google/repo_1/issues{/number}",
        "pulls_url": "https://api.github.com/repos/google/repo_1/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/google/repo_1/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/google/repo_1/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/google/repo_1/labels{/name}",
        "releases_url": "https://api.github.com/repos/google/repo_1/releases{/id}",
        "deployments_url": "https://api.github.com/repos/google/repo_1/deployments",
        "created_at": "2018-01-01T00:00:00Z",
        "updated_at": "2024-07-17T19:30:18Z",
        "pushed_at": "2024-07-17T19:30:18Z",
        "git_url": "git://github.com/google/repo_1.git",
        "ssh_url": "git@github.com:google/repo_1.git",
        "clone_url": "https://github.com/google/repo_1.git",
        "svn_url": "https://github.com/google/repo_1",
        "homepage": None,
        "size": 0,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "has_discussions": False,
        "forks_count": 0,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 0,
        "license": {"key": "apache-2.0", "name": "Apache License 2.0", "spdx_id": "Apache-2.0", "url": "https://api.github.com/licenses/apache-2.0", "node_id": "MDc6TGljZW5zZTI="},
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
    },
    {
        "id": 987654321,
        "node_id": "MDEwOlJlcG9zaXRvcnk5ODc2NTQzMjE=",
        "name": "repo_2",
        "full_name": "google/repo_2",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1342004?v=4",
        },
        "html_url": "https://github.com/google/repo_2",
        "description": "Another sample repository.",
        "fork": False,
        "url": "https://api.github.com/repos/google/repo_2",
        "forks_url": "https://api.github.com/repos/google/repo_2/forks",
        "keys_url": "https://api.github.com/repos/google/repo_2/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/google/repo_2/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/google/repo_2/teams",
        "hooks_url": "https://api.github.com/repos/google/repo_2/hooks",
        "issue_events_url": "https://api.github.com/repos/google/repo_2/issues/events{/number}",
        "events_url": "https://api.github.com/repos/google/repo_2/events",
        "assignees_url": "https://api.github.com/repos/google/repo_2/assignees{/user}",
        "branches_url": "https://api.github.com/repos/google/repo_2/branches{/branch}",
        "tags_url": "https://api.github.com/repos/google/repo_2/tags",
        "blobs_url": "https://api.github.com/repos/google/repo_2/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/google/repo_2/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/google/repo_2/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/google/repo_2/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/google/repo_2/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/google/repo_2/languages",
        "stargazers_url": "https://api.github.com/repos/google/repo_2/stargazers",
        "contributors_url": "https://api.github.com/repos/google/repo_2/contributors",
        "subscribers_url": "https://api.github.com/repos/google/repo_2/subscribers",
        "subscription_url": "https://api.github.com/repos/google/repo_2/subscription",
        "commits_url": "https://api.github.com/repos/google/repo_2/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/google/repo_2/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/google/repo_2/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/google/repo_2/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/google/repo_2/contents/{+path}",
        "compare_url": "https://api.github.com/repos/google/repo_2/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/google/repo_2/merges",
        "archive_url": "https://api.github.com/repos/google/repo_2/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/google/repo_2/downloads",
        "issues_url": "https://api.github.com/repos/google/repo_2/issues{/number}",
        "pulls_url": "https://api.github.com/repos/google/repo_2/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/google/repo_2/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/google/repo_2/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/google/repo_2/labels{/name}",
        "releases_url": "https://api.github.com/repos/google/repo_2/releases{/id}",
        "deployments_url": "https://api.github.com/repos/google/repo_2/deployments",
        "created_at": "2018-01-02T00:00:00Z",
        "updated_at": "2024-07-17T19:30:18Z",
        "pushed_at": "2024-07-17T19:30:18Z",
        "git_url": "git://github.com/google/repo_2.git",
        "ssh_url": "git@github.com:google/repo_2.git",
        "clone_url": "https://github.com/google/repo_2.git",
        "svn_url": "https://github.com/google/repo_2",
        "homepage": None,
        "size": 0,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Java",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "has_discussions": False,
        "forks_count": 0,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 0,
        "license": None,
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
    },
    {
        "id": 112233445,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMTIyMzM0NDU=",
        "name": "repo_3_apache",
        "full_name": "google/repo_3_apache",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1342004?v=4",
        },
        "html_url": "https://github.com/google/repo_3_apache",
        "description": "Another sample repository with Apache license.",
        "fork": False,
        "url": "https://api.github.com/repos/google/repo_3_apache",
        "license": {"key": "apache-2.0", "name": "Apache License 2.0", "spdx_id": "Apache-2.0", "url": "https://api.github.com/licenses/apache-2.0", "node_id": "MDc6TGljZW5zZTI="},
        "forks_count": 0,
        "open_issues_count": 0,
        "watchers_count": 0,
        "default_branch": "main",
    }
]

expected_repos = [
    "repo_1",
    "repo_2",
    "repo_3_apache"
]

apache2_repos = [
    "repo_1",
    "repo_3_apache"
]
apache2_repos = ["repo1", "repo3"]
